### ISSUE TITLE
m3u export with direct stream url's

### ISSUE THREAD

**Issue by oatmealm** [matthuisman/slyguy.iptv.merge.example#2]
Hi. Thanks for this great plugin.
Was wondering if it's possible to export m3u of merged playlists that contains direct stream URL's when source is some kodi add-on, like Pluto TV or other. Right now, it exports them with the plugin:// protocol, which can't be played in other IPTV client's. i.e. Jellyfin etc., where I'm consuming the exported playlist. 
10x

**Comment by matthuisman** [comment]
No sorry. It's the addons themselves returning those paths. Have a hunt online, there will be a Pluto playlist
